package edu.whu.gitool.subcommand.command

enum class SubCommandEnum(val commandName: String) {
    FIND("find"),
    CLONE("clone"),
    EXTRACT("extract"),
    VALIDATE("validate");

    class Descriptions {
        companion object {
            const val FIND = "find merge scenario"
            const val CLONE = "clone local repo or remote repo to local"
            const val EXTRACT = "extract merge scenario(our, base, their, merged) to local"
            const val VALIDATE =
                "validate the precession of merge resolution generated by other tools"
        }
    }
}
