/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package edu.whu.gitool

import org.slf4j.LoggerFactory


class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

private val logger = LoggerFactory.getLogger("gitool")

fun main() {
    logger.info("hello from logger")
    println("Hello world!")
}
